#!/bin/sh
#
# ifspace - run a command if there is enough space in a filesystem
#
# @(#) $Revision$
# @(#) $Id$
# @(#) $Source$
#
# Copyright (c) 2004 by Landon Curt Noll.  All Rights Reserved.
#
# Permission to use, copy, modify, and distribute this software and
# its documentation for any purpose and without fee is hereby granted,
# provided that the above copyright, this permission notice and text
# this comment, and the disclaimer below appear in all of the following:
#
#       supporting documentation
#       source copies
#       source works derived from this source
#       binaries derived from this source or from derived source
#
# LANDON CURT NOLL DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE,
# INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO
# EVENT SHALL LANDON CURT NOLL BE LIABLE FOR ANY SPECIAL, INDIRECT OR
# CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF
# USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
# OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
# PERFORMANCE OF THIS SOFTWARE.
#
# chongo (Landon Curt Noll, http://www.isthe.com/chongo/index.html) /\oo/\
#
# Share and enjoy! :-)

# parse args
#
if [[ $# -lt 4 ]]; then
    echo "usage: $0 /file/sys kbytefree cmd [arg ...]" 1>&2
    exit 1
fi
PROGRAM="$0"
FILESYS="$1"
NEEDKFREE="$2"
if [[ ! -e "$FILESYS" ]]; then
    echo "$0: does not exist: $FILESYS" 1>&2
    exit 2
fi

# determine free space
#
KFREE=$(/bin/df -k -P "$FILESYS" | /bin/sed -n 2p | /bin/awk '{print $4;}')

# execute command if there is enough space
#
if [[ "$KFREE" -ge "$NEEDKFREE" ]]; then
    shift 2
    $@
    STATUS="$?"
else
    STATUS="0"
fi
exit "$STATUS"
